### ISSUE TITLE
MHX Quest editor

### ISSUE THREAD

**Issue by kcdra** [svanheulen/mhxqe#1]
the mission does not appear

**Comment by svanheulen** [comment]
The 1.2 update added some limitations on what you can do with custom quests. For instance you can't put more then 10 of an item in the supply box. I'm not sure what all the limitation are but you're most likely changing something that the game doesn't like.

You could try deleting the 1.2 update and see if the game lets you post the quest. Keep in mind that you'll have to re-import the quest after you remove the 1.2 update though.

You can also try to narrow down what exactly is causing the issue by only making one change at a time and test them until it stops showing up.

**Comment by kcdra** [comment]
Wow, really works, thanks for the "tutorial".
I just need to remove the update that appeared the Custom Quests.

2016-05-22 0:02 GMT-03:00 Seth VanHeulen notifications@github.com:
