### ISSUE TITLE
Add "Hyper" status to Icons

### ISSUE THREAD

**Issue by phecdaDia** [svanheulen/mhxqe#2]
Icons with the "Hyper" status are the original offset + 120.  
Creating a checkbox next to the dropbox for the icons that increases the value for the icon by 120 would allow users to create icons for hyper monster icons.

**Comment by svanheulen** [comment]
Thanks for figuring that out. And yeah, I think a checkbox would be best. I'll work on adding that tomorrow.

**Comment by svanheulen** [comment]
Should be working now. Can you please test it and let me know if it's working ok?

**Comment by phecdaDia** [comment]
Seems to be working. Created a quest with a hyper deviljho as icon some days ago when I forked it for some testing.  
I uploaded it and it showed me Hyper deviljho. When downloading it and comparing the sha1sum of both .arc files they matched.   

So it seems to be working :+1:

**Comment by svanheulen** [comment]
Awesome, thanks for testing it and thanks again for figuring it out :)
