### ISSUE TITLE
Mhxqe deviants

### ISSUE THREAD

**Issue by UnlimitedTriHard** [svanheulen/mhxqe#3]
How to make custom quest with deviants on them? I can make the quest appear and make them spawn, but they have weird hp numbers (using cheat to see hp) and they also have the minimum amount of damage.

**Comment by svanheulen** [comment]
I have no idea, I've never tried adding a deviant. Did you try changing any of the attack table or difficulty options or maybe the star level? If you can, it would probably help to extract the game's romfs and see what they do in one of the actual special permit quests.

**Comment by UnlimitedTriHard** [comment]
I tried all the options, none of them worked. Yeah if anyone figures that out that'd be great.

**Comment by phecdaDia** [comment]
Give me a minute.

**Comment by imthe666st** [comment]
I dumped the quests. Feel free to download them from https://drive.google.com/file/d/0B0_wMBqyr823TzNSeVdIX1NXSjg/view?usp=sharing

**Comment by svanheulen** [comment]
Sorry @imthe666st I can't let you post those :(
Copyright and such.

**Comment by phecdaDia** [comment]
Alright. Understandable. I'm sorry.

**Comment by phecdaDia** [comment]
Anyways, I can't seem to find a difference in the values for deviants and normal monsters.

**Comment by UnlimitedTriHard** [comment]
@imthe666st did you figure out how to make the deviants work in custom, what is their monster id?

**Comment by phecdaDia** [comment]
@UnlimitedTriHard Their MonsterIDs are DeviantMonsterID = 0x400 | MonsterID.  
The monster ids are already in the editor.

**Comment by UnlimitedTriHard** [comment]
@imthe666st if it's 10## how do you fit that, it's only 3 digit on the emmain, if I put all 4 digits of say dreadking (1025) the monsters vanish.

**Comment by phecdaDia** [comment]
I'm sorry, what does "emmain" mean?

**Comment by UnlimitedTriHard** [comment]
quest\boss\setEmMain\b_m00em000_00 on the quest editor online.

**Comment by phecdaDia** [comment]
You have to choose the monster in the rQuestData file.  
https://gyazo.com/8f9bf7c1586c9678acd4ecfbfa064120.png

**Comment by UnlimitedTriHard** [comment]
you still have to link him to the em main file though don't you? That's how I got them to work.

**Comment by phecdaDia** [comment]
Yes, you need a file reference.  
At the bottom of the rQuestData file you have to say in which rSetEmMain are the position and rotation of your monster. https://gyazo.com/22a6fe39b4b8a992f5a72636373f9007.png

**Comment by UnlimitedTriHard** [comment]
Yeah and the em number matches the one on top like 10 is plesioth or something. Anyways I still can't figure out how to make deviant monsters not do 1 damage per hit. I think I'll just give up until someone figures it out.

**Comment by phecdaDia** [comment]
You can choose whatever name you want. I'd suggest a different writing anyways, since you can theoretically override other stuff.  
Just create your own rSetEmMain files up like this: quest\boss\setEmMain\b_q[id]_[monster#] it works too.   So for example the azuros from my example would be quest\boss\setEmMain\b_q00040110_2

**Comment by Arubatorion722** [comment]
what do i do once ive made the file and downloaded it to my pc?

**Comment by svanheulen** [comment]
@Lesoith Use this homebrew app to import the quest into your save file: https://github.com/svanheulen/mhx_data_manager
