### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by deppins** [svanheulen/mhxqe#4]
I was wondering if you could provide me with a tutorial on how to use the custom quest editor. I already have access to my save file and homebrew, I need help on how to move forward from where i am now.

**Comment by svanheulen** [comment]
First use my MHX Data Manager homebrew to extract the quests from your save file: https://github.com/svanheulen/mhx_data_manager/releases
Copy the extracted quests to your computer and open them with the editor.

**Comment by svanheulen** [comment]
Closing since there has been no response in 2 weeks.
