### ISSUE TITLE
Random boss spawn possible?

### ISSUE THREAD

**Issue by helium7** [svanheulen/mhxqe#5]
Hi, im trying to create an arena map that spawn random monster, e.g. first time u enter its a zingore, the nxt time you try the quest is a jho. I tried add afew sem\emmain but its doesnt seems to work. Would be glad if you can provide some advice or if its possible!

**Comment by svanheulen** [comment]
I would try leaving the boss monster 1 and 2 empty and setting boss monsters 3-5. There are "intruder" options in the `rQuestData` file type that lets you give those bosses a random chance of spawning. You'll also probably want to set the main objective to "Hunt All Large Monsters"

**Comment by helium7** [comment]
Hi, thanks for the reply! Does this means the boss will only random between 3-5? so i have to
Add > select and chose 3 quest\boss\setEmMain\ 
Check > intruder under quest\questData\questData
Select > boss details 3,4,5  under quest\questData\questData
fill up > intruder settings for quest\questData\questData
change > mission objective to hunt all monster for quest\questData\questData

**Comment by svanheulen** [comment]
Exactly... but that's just my theory, I haven't actually tested it.
