### ISSUE TITLE
No Leveled Deviants

### ISSUE THREAD

**Issue by Phemeto** [svanheulen/mhxqe#6]
I've been working on trying to figure out how to get the leveled deviants (DQ5+ has Toxic, Silverwind 5+ has double tail slam, etc) into CQ, but They always appear at their low-level counterpart. Even after taking a Variant X quest (which works fine) and just changing the quest ID, as soon as it comes out of the editor, the monsters are downgraded to their lower level counterparts. Not sure if there's a different ID for the leveled ones or not, but it is missing.

**Comment by svanheulen** [comment]
The quest editor wont modify anything except what you explicitly tell it to. So if just changing the quest ID messes up the Deviant level, that must mean that they need to have a ["special permit"](https://github.com/svanheulen/mhff/wiki/MHX-rQuestData-Format#quest-id) quest ID for them to work properly. Unfortunately there is a list of valid DLC quest IDs built into the game. So the quest IDs in the quest editor's dropdown list are the only ones you can use and still have your quest show up in the game.

I'm going to close #3 and leave this issue open for future reference.

**Comment by Pr1am** [comment]
I've also been fairly interested in this as well, and after viewing the rQuestData format, I was wondering about how one would access that format in the first place to change the Quest ID decimal format to spawn an appropriate deviant of a difficulty between levels 1-10. Is there anyway to access that through the web editor and, if not, how could one access it? Thanks!

**Comment by svanheulen** [comment]
Sorry for the delayed reply @Pr1am 
The issue with that is that the Quest IDs you can select in the editor are the **only** ones that the game will accept for DLC quests. If you did manually change to Quest ID to match the deviant difficulty, it wouldn't be accessible anywhere in the game.
