### ISSUE TITLE
Mission crash due to setEmMain file name

### ISSUE THREAD

**Issue by Mowstyl** [svanheulen/mhxqe#7]
When creating a mission in Forlorn Arena, I've found that the name of the setEmMain files should start with b_m17emYYY_ZZ. Otherwise, the quest would crash.
Maybe, b_mXXemYYY_ZZ follows this syntax:
XX -> Map ID (Checked at quest load)
YYY -> Monster ID (Not checked)
ZZ -> Monster Number (If there are more than one of the same type)

If this is true, it'll be nice to add it, or at least to state it somewhere.
Thanks,

Mowstyl.

**Comment by phecdaDia** [comment]
In my experience, the name of the files didn't matter. Make sure you adjust the reference in the main file as well as just the file name itself.

**Comment by Mowstyl** [comment]
It matters, specially the map ID. The references were correct but the quest didn't worked until I put the correct map ID after the m in the name of the file and updated it again.
