### ISSUE TITLE
Rewards are not given as they should.

### ISSUE THREAD

**Issue by Mowstyl** [svanheulen/mhxqe#8]
Creating a custom quest and testing the rewards, I've found that even if I put a 100% chance to an item, only a few of them are given.
Maybe there is something I'm missing?
Also, there is a specific syntax to be followed when writing rRem file name?
Thanks in advance,

Mowstyl.

**Comment by phecdaDia** [comment]
The name of the files don't matter, however, try setting the chance to 255, instead of 100. Some items can't be set as rewards.

**Comment by Mowstyl** [comment]
I tried to set it to 255 but then there was no reward. The items that I set as rewards were given by other quests so thats not the problem.

**Comment by Mowstyl** [comment]
Is it possible to have a 100% chance or the game just doesn't allow that?
